function uml()
%% Generate PlantUML code for COSMOS software.
%_____________________________________________________________________
%
% Function docs:
%
% Detailed explanation goes here.
%_____________________________________________________________________

% Get directory of this matlab file.
[filepath,~,~] = fileparts(mfilename('fullpath'));

% Change working directory to the directory of this m-file.
cd(filepath);

% Add m2uml and lib folders to the current MATLAB path.
addpath(strcat('.',filesep,'m2uml',filesep));
addpath(strcat('.',filesep,'lib',filesep));

% Import package m2uml with all its classes and functions.
import m2uml.*

% Notes on how to set relations between classes:
% - Association occurs when two classes in a model need to ...
%   communicate with each other; it is represent by the connector ...
%   '-->' in which the direction of the arrow indicates the ...
%   navigation direction; in case an arrow is on both sides, the ...
%   association is known as a bidirectional association.
% - Aggregation and Composition both imply that the object of one ...
%   class owns the object of another class.
% - Aggregation implies a relationship where the child can exist ...
%   independently of the parent; if the parent class is deleted, ...
%   the child class still exists; it is represented by the ...
%   connector 'o--' in PlantUML.
% - Composition implies a relationship where the child cannot ...
%   exist independently of the parent; if the parent class is ...
%   deleted, the child class cannot exist alone; it is represented ...
%   by the connector '*--' in PlantUML.

% Run tool m2uml.
[~] = m2uml.run('CosmosFS', ...
	{ ...
		'Main', ...
		'IvanovFormationFlight', ...
		'CosmosSimulation', ...
		'Orbit', ...
		'IvanovSatellite' ...
	} , { ...
		%'Main "1" o-- "1" IvanovFormationFlight', ...
		%'Main "1" *-- "0..1" CosmosSimulation', ...
		'IvanovFormationFlight "1" o-- "1..*" IvanovSatellite', ...
		'IvanovFormationFlight "1" o-- "1" Orbit'
	} ...
);

end
