function createfigureEarthRotation(X1, ymatrix1, Parent1)
%CREATEFIGURE(X1, ymatrix1, Parent1)
%  X1:  stairs x
%  YMATRIX1:  stairs matrix data
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 13-Jul-2020 11:11:19

% Create figure
figure('Tag','ScopePrintToFigure',...
    'Color',[0.156862745098039 0.156862745098039 0.156862745098039],...
    'OuterPosition',[1 1 2048 950.4]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('Tag','DisplayAxes1_RealMag',...
    'Position',[0.00671359677464567 0.034762298061678 0.988397861966066 0.954932673084241]);
hold(axes1,'on');
colororder([1 1 0.0666666666666667;0.0745098039215686 0.623529411764706 1;1 0.411764705882353 0.16078431372549;0.392156862745098 0.831372549019608 0.0745098039215686;0.717647058823529 0.274509803921569 1;0.0588235294117647 1 1;1 0.0745098039215686 0.650980392156863]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create multiple lines using matrix input to stairs
stairs1 = stairs(X1,ymatrix1,'LineWidth',0.75,'Parent',axes1);
set(stairs1(1),'DisplayName','Rate Transition7:1','Tag','DisplayLine1',...
    'Color',[1 1 0.0666666666666667]);
set(stairs1(2),'DisplayName','Rate Transition7:2','Tag','DisplayLine2',...
    'Color',[0.0745098039215686 0.623529411764706 1]);
set(stairs1(3),'DisplayName','Rate Transition7:3','Tag','DisplayLine3',...
    'Color',[1 0.411764705882353 0.16078431372549]);
set(stairs1(4),'DisplayName','Rate Transition7:4','Tag','DisplayLine4',...
    'Color',[0.392156862745098 0.831372549019608 0.0745098039215686]);

% Create xlabel
xlabel(' ');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 200000.000000001]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.91038085041447 7.19342765388173]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','Color',[0 0 0],'ContextMenu',...
    'FontSize',8,'GridAlpha',0.4,'GridColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none','XColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],'XGrid','on',...
    'YColor',[0.686274509803922 0.686274509803922 0.686274509803922],'YGrid',...
    'on','ZColor',[0.686274509803922 0.686274509803922 0.686274509803922]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Units','pixels',...
    'TextColor',[0.882062358925529 0.882062358925529 0.882062358925529],...
    'Position',[1888.13333125432 891.233322751095 138.20000207901 59.9000012969964],...
    'Interpreter','none',...
    'FontSize',8,...
    'EdgeColor',[0.882062358925529 0.882062358925529 0.882062358925529]);

% Create text
text('Tag','TimeOffsetStatus','Parent',Parent1,'Units','pixels',...
    'VerticalAlignment','bottom',...
    'FontSize',8,...
    'Position',[0 0 0],...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'Visible','on');

